### ISSUE TITLE
Variants

### ISSUE THREAD

**Issue by Azertyuiop442** [no-clicks/Chat-GPT-Giphy-Connector#13]
Hello,
I would like to know how it is possible to have variants, for example, if I enter Search = Sun it will show me a gif of the sun until now everything is fine, but if I enter the command a second time I get the same gif. Is it possible to have a variant?

**Comment by RazyAnas** [comment]
Make a prompt for ChatGPT and it will automatically change the search phrase different everytime to create variations.

**Comment by RazyAnas** [comment]
> Hello, I would like to know how it is possible to have variants, for example, if I enter Search = Sun it will show me a gif of the sun until now everything is fine, but if I enter the command a second time I get the same gif. Is it possible to have a variant?

You just need to make a prompt for ChatGPT such that it will automatically change the search phrase everytime to create variations.

**Comment by no-clicks** [comment]
The result for the term passed is cached for awhile, so getting a different image for the same term isn't current functionality. I believe the idea was to get the best result for each term.

As RazyAnas suggests, you could definitely ask chatGPT for a similar gif or a variant. That may get you a different result. Chat GPT is really just putting together search term combinations to pass to giphy.
