### ISSUE TITLE
Project suspended from glitch.me

### ISSUE THREAD

**Issue by RazyAnas** [no-clicks/Chat-GPT-Giphy-Connector#14]
![Screenshot_2023-05-07-11-19-01-68_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/59137612/236660107-ebfd413c-8286-44d3-9beb-da479b6bce2a.jpg)

Oops! This project isn't running.
If this is your project, check out the [Glitch Editor](http://glitch.com/edit/#!/scythe-spot-carpenter), or head over to the Help Center to [learn more](https://glitch.com/help/kb/article/72).

After clicking on learn more: Reason for suspension: Violating Terms of Service. SKM
If you think this was done in error, email support@glitch.com

**Comment by no-clicks** [comment]
Thank you for the notification! I was able to speak with Glitch and we were able to get it running again. Looks like the project falsely flagged in their system. I apologize for taking so long to get this resolved. Everything appears to be functioning normally again at this time.
